version: '3.9'
services:
  flow-pdf-dev:
    build:
      context: ./src/flow_pdf
      dockerfile: Dockerfile_dev

    container_name: flow-pdf-dev
    # restart: unless-stopped
    volumes:
        - '${INPUT_PATH}:/workspace/flow_pdf/data/input'
        - '${LAYOUT_PARSER_OUTPUT_PATH}:/workspace/flow_pdf/data/layout-parser-output'

        - '${FLOWPDF_OUTPUT_PATH}:/workspace/flow_pdf/data/flow_pdf_output'

        - './src/flow_pdf:/workspace/flow_pdf'
        - './vsc_extensions/flow_pdf:/root/.vscode-server/extensions'
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
  flow-pdf-fe-dev:
    build:
      context: ./src/fe
      dockerfile: Dockerfile_dev
    container_name: flow-pdf-fe-dev

    volumes:
      - './src/fe:/workspace/fe'

      - './vsc_extensions/fe:/root/.vscode-server/extensions'
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    deploy:
      replicas: ${ENABLE_FE}
  layout-parser-dev:
    build:
      context: ./src/layout-parser
      dockerfile: Dockerfile

    container_name: layout-parser-dev
    # restart: unless-stopped
    volumes:
        - '${INPUT_PATH}:/workspace/layout-parser/data/input'
        - '${LAYOUT_PARSER_OUTPUT_PATH}:/workspace/layout-parser/data/layout-parser-output'

        - './src/layout-parser:/workspace/layout-parser'
        - './vsc_extensions/layout-parser:/root/.vscode-server/extensions'
    deploy:
      replicas: ${ENABLE_LAYOUT_PARSER}
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    stdin_open: true
    tty: true
  nougat-demo-dev:
    build:
      context: ./experiment/nougat-demo
      dockerfile: Dockerfile

    container_name: nougat-demo-dev
    # restart: unless-stopped
    volumes:
      - '${INPUT_PATH}:/workspace/nougat-demo/data/input'
      - '${NOUGAT_OUTPUT_PATH}:/workspace/nougat-demo/data/output'

        # - '${FLOWPDF_OUTPUT_PATH}:/workspace/nougat-demo/data/nougat-demo_output'

      - ./experiment/nougat-demo:/workspace/nougat-demo
      - './vsc_extensions/nougat-demo:/root/.vscode-server/extensions'
    ports:
      - '8503:8503'
    stdin_open: true
    tty: true
    deploy:
      replicas: ${ENABLE_EXP_NOUGAT}
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  nougat-dev:
    build:
      context: ./src/nougat
      dockerfile: Dockerfile_dev

    container_name: nougat-dev
    # restart: unless-stopped
    volumes:
      # - '${INPUT_PATH}:/workspace/nougat/data/input'
      # - '${NOUGAT_OUTPUT_PATH}:/workspace/nougat/data/output'

        # - '${FLOWPDF_OUTPUT_PATH}:/workspace/nougat-demo/data/nougat-demo_output'

      - ./src/nougat:/workspace/nougat
      - './vsc_extensions/nougat:/root/.vscode-server/extensions'
    ports:
      - '8503:8503'
    stdin_open: true
    tty: true
    deploy:
      replicas: ${ENABLE_NOUGAT}
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  fc-local-dev-dev:
    build:
      context: ./src/fc-local-dev
      dockerfile: Dockerfile_dev

    container_name: fc-local-dev-dev
    # restart: unless-stopped
    volumes:
        - './src/fc-local-dev:/workspace/fc-local-dev'
        - './vsc_extensions/fc-local-dev:/root/.vscode-server/extensions'
        - '/var/run/docker.sock:/var/run/docker.sock:ro'
    stdin_open: true
    tty: true