version: '3.9'
services:
  flow-pdf:
    image: '117503445/flow-pdf'
    container_name: flow-pdf
    restart: unless-stopped
    volumes:
        - './web-data:/root/app/flow_pdf/web-data'
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          memory: 8G